[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@solmate/=lib/solmate/src/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
[fuzz]
runs = 256

# [rpc_endpoints]
# sepolia = "https://eth-sepolia.g.alchemy.com/v2/HS5F308oatduaLI_WvBDj"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
